require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe DatasheetsController do

  # This should return the minimal set of attributes required to create a valid
  # Datasheet. As you add validations to Datasheet, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "user_id" => "1" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # DatasheetsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all datasheets as @datasheets" do
      datasheet = Datasheet.create! valid_attributes
      get :index, {}, valid_session
      assigns(:datasheets).should eq([datasheet])
    end
  end

  describe "GET show" do
    it "assigns the requested datasheet as @datasheet" do
      datasheet = Datasheet.create! valid_attributes
      get :show, {:id => datasheet.to_param}, valid_session
      assigns(:datasheet).should eq(datasheet)
    end
  end

  describe "GET new" do
    it "assigns a new datasheet as @datasheet" do
      get :new, {}, valid_session
      assigns(:datasheet).should be_a_new(Datasheet)
    end
  end

  describe "GET edit" do
    it "assigns the requested datasheet as @datasheet" do
      datasheet = Datasheet.create! valid_attributes
      get :edit, {:id => datasheet.to_param}, valid_session
      assigns(:datasheet).should eq(datasheet)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Datasheet" do
        expect {
          post :create, {:datasheet => valid_attributes}, valid_session
        }.to change(Datasheet, :count).by(1)
      end

      it "assigns a newly created datasheet as @datasheet" do
        post :create, {:datasheet => valid_attributes}, valid_session
        assigns(:datasheet).should be_a(Datasheet)
        assigns(:datasheet).should be_persisted
      end

      it "redirects to the created datasheet" do
        post :create, {:datasheet => valid_attributes}, valid_session
        response.should redirect_to(Datasheet.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved datasheet as @datasheet" do
        # Trigger the behavior that occurs when invalid params are submitted
        Datasheet.any_instance.stub(:save).and_return(false)
        post :create, {:datasheet => { "user_id" => "invalid value" }}, valid_session
        assigns(:datasheet).should be_a_new(Datasheet)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Datasheet.any_instance.stub(:save).and_return(false)
        post :create, {:datasheet => { "user_id" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested datasheet" do
        datasheet = Datasheet.create! valid_attributes
        # Assuming there are no other datasheets in the database, this
        # specifies that the Datasheet created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Datasheet.any_instance.should_receive(:update).with({ "user_id" => "1" })
        put :update, {:id => datasheet.to_param, :datasheet => { "user_id" => "1" }}, valid_session
      end

      it "assigns the requested datasheet as @datasheet" do
        datasheet = Datasheet.create! valid_attributes
        put :update, {:id => datasheet.to_param, :datasheet => valid_attributes}, valid_session
        assigns(:datasheet).should eq(datasheet)
      end

      it "redirects to the datasheet" do
        datasheet = Datasheet.create! valid_attributes
        put :update, {:id => datasheet.to_param, :datasheet => valid_attributes}, valid_session
        response.should redirect_to(datasheet)
      end
    end

    describe "with invalid params" do
      it "assigns the datasheet as @datasheet" do
        datasheet = Datasheet.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Datasheet.any_instance.stub(:save).and_return(false)
        put :update, {:id => datasheet.to_param, :datasheet => { "user_id" => "invalid value" }}, valid_session
        assigns(:datasheet).should eq(datasheet)
      end

      it "re-renders the 'edit' template" do
        datasheet = Datasheet.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Datasheet.any_instance.stub(:save).and_return(false)
        put :update, {:id => datasheet.to_param, :datasheet => { "user_id" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested datasheet" do
      datasheet = Datasheet.create! valid_attributes
      expect {
        delete :destroy, {:id => datasheet.to_param}, valid_session
      }.to change(Datasheet, :count).by(-1)
    end

    it "redirects to the datasheets list" do
      datasheet = Datasheet.create! valid_attributes
      delete :destroy, {:id => datasheet.to_param}, valid_session
      response.should redirect_to(datasheets_url)
    end
  end

end
